import { Product } from "../modules/table/models/product/Product.model";

export const mock_products: Product[] = [
    new Product({
        id: 1,
        name: 'Pizza Margherita',
        idCategory: 1,
        price: 25.00,
        description: 'Pizza Margherita',
        image: 'https://www.pizzaprimo.it/wp-content/uploads/2019/03/pizza-margherita.jpg',
    }),
    new Product({
        id: 2,
        name: 'Pizza Marinara',
        idCategory: 1,
        price: 27.00,
        description: 'Pizza Marinara',
        image: 'https://www.pizzaprimo.it/wp-content/uploads/2019/03/pizza-marinara.jpg',
    }),
    new Product({
        id: 3,
        name: 'Pizza Quattro Stagioni',
        idCategory: 1,
        price: 33.00,
        description: 'Pizza Quattro Stagioni',
        image: 'https://www.pizzaprimo.it/wp-content/uploads/2019/03/pizza-quattro-stagioni.jpg',
    }),
    new Product({
        id: 4,
        name: 'Pizza Quattro Formaggi',
        idCategory: 1,
        price: 32.00,
        description: 'Pizza Quattro Formaggi',
        image: 'https://www.pizzaprimo.it/wp-content/uploads/2019/03/pizza-quattro-formaggi.jpg',
    }),
    new Product({
        id: 5,
        name: 'Pizza Capricciosa',
        idCategory: 1,
        price: 30.00,
        description: 'Pizza Capricciosa',
        image: 'https://www.pizzaprimo.it/wp-content/uploads/2019/03/pizza-capricciosa.jpg',
    }),
    new Product({
        id: 6,
        name: 'Pizza Funghi',
        idCategory: 1,
        price: 30.00,
        description: 'Pizza Funghi',
        image: 'https://www.pizzaprimo.it/wp-content/uploads/2019/03/pizza-funghi.jpg',
    }),
    new Product({
        id: 7,
        name: 'Pizza Prosciutto',
        idCategory: 1,
        price: 28.00,
        description: 'Pizza Prosciutto',
        image: 'https://www.pizzaprimo.it/wp-content/uploads/2019/03/pizza-prosciutto.jpg',
    }),
    new Product({
        id: 8,
        name: 'Pizza Tonno',
        idCategory: 1,
        price: 27.00,
        description: 'Pizza Tonno',
        image: 'https://www.pizzaprimo.it/wp-content/uploads/2019/03/pizza-tonno.jpg',
    }),
    new Product({
        id: 9,
        name: 'Pizza Vegetariana',
        idCategory: 1,
        price: 26.00,
        description: 'Pizza Vegetariana',
        image: 'https://www.pizzaprimo.it/wp-content/uploads/2019/03/pizza-vegetariana.jpg',
    }),
    new Product({
        id: 10,
        name: 'Pizza Bolognese',
        idCategory: 1,
        price: 26.00,
        description: 'Pizza Bolognese',
        image: 'https://www.pizzaprimo.it/wp-content/uploads/2019/03/pizza-bolognese.jpg',
    }),
    new Product({
        id: 11,
        name: 'Pizza Calzone',
        idCategory: 1,
        price: 25.00,
        description: 'Pizza Calzone',
        image: 'https://www.pizzaprimo.it/wp-content/uploads/2019/03/pizza-calzone.jpg',
    }),
    new Product({
        id: 12,
        name: 'Pizza Diavola',
        idCategory: 1,
        price: 28.00,
        description: 'Pizza Diavola',
        image: 'https://www.pizzaprimo.it/wp-content/uploads/2019/03/pizza-diavola.jpg',
    }),
    new Product({
        id: 13,
        name: 'Pizza Hawaii',
        idCategory: 1,
        price: 34.00,
        description: 'Pizza Hawaii',
        image: 'https://www.pizzaprimo.it/wp-content/uploads/2019/03/pizza-hawaii.jpg',
    }),
    new Product({
        id: 14,
        name: 'Coca Cola',
        idCategory: 2,
        price: 6.00,
        description: 'Coca Cola',
        image: 'https://www.pizzaprimo.it/wp-content/uploads/2019/03/coca-cola.jpg',
    }),
    new Product({
        id: 15,
        name: 'Fanta',
        idCategory: 2,
        price: 6.00,
        description: 'Fanta',
        image: 'https://www.pizzaprimo.it/wp-content/uploads/2019/03/fanta.jpg',
    }),
    new Product({
        id: 16,
        name: 'Sprite',
        idCategory: 2,
        price: 6.00,
        description: 'Sprite',
        image: 'https://www.pizzaprimo.it/wp-content/uploads/2019/03/sprite.jpg',
    }),
    new Product({
        id: 17,
        name: 'Apă Plată',
        idCategory: 2,
        price: 5.00,
        description: 'Apă Plată',
        image: 'https://www.pizzaprimo.it/wp-content/uploads/2019/03/acqua.jpg',
    }),
    new Product({
        id: 18,
        name: 'Caffè Latte',
        idCategory: 3,
        price: 12.00,
        description: 'Caffè Latte',
        image: 'https://www.pizzaprimo.it/wp-content/uploads/2019/03/caffe.jpg',
    }),
    new Product({
        id: 19,
        name: 'Sauvignon Blanc',
        idCategory: 4,
        price: 30.00,
        description: 'Sauvignon Blanc',
        image: 'https://www.pizzaprimo.it/wp-content/uploads/2019/03/sauvignon-blanc.jpg',
    }),
    new Product({
        id: 20,
        name: 'Birra Moretti',
        idCategory: 5,
        price: 8.00,
        description: 'Birra Moretti',
        image: 'https://www.pizzaprimo.it/wp-content/uploads/2019/03/birra-moretti.jpg',
    }),
    new Product({
        id: 21,
        name: 'Păstrăv File',
        idCategory: 6,
        price: 30.00,
        description: 'Păstrăv File',
        image: 'https://www.pizzaprimo.it/wp-content/uploads/2019/03/pastrav-file.jpg',
    }),
    new Product({
        id: 22,
        name: 'Jack Daniels',
        idCategory: 7,
        price: 30.00,
        description: 'Jack Daniels',
        image: 'https://www.pizzaprimo.it/wp-content/uploads/2019/03/jack-daniels.jpg',
    }),
    new Product({
        id: 23,
        name: 'Piure de cartofi',
        idCategory: 8,
        price: 10.00,
        description: 'Piure de cartofi',
        image: 'https://www.pizzaprimo.it/wp-content/uploads/2019/03/piure-de-cartofi.jpg',
    }),
    new Product({
        id: 24,
        name: 'Ceafă de porc',
        idCategory: 9,
        price: 28.00,
        description: 'Ceafă de porc',
        image: 'https://www.pizzaprimo.it/wp-content/uploads/2019/03/ceafa-de-porc.jpg',
    }),
    new Product({
        id: 25,
        name: 'Ciorbă de burtă',
        idCategory: 10,
        price: 23.00,
        description: 'Ciorbă de burtă',
        image: 'https://www.pizzaprimo.it/wp-content/uploads/2019/03/ciorba-de-burta.jpg',
    }),
    new Product({
        id: 26,
        name: 'Icre de somon',
        idCategory: 11,
        price: 5.00,
        description: 'Icre de somon',
        image: 'https://www.pizzaprimo.it/wp-content/uploads/2019/03/icre-de-somon.jpg',
    })
];